# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Aug 19 13:18:49 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(973, 815)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 661, 611))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMinDistance = QtGui.QWidget()
        self.tabMinDistance.setObjectName(_fromUtf8("tabMinDistance"))
        self.label_desc = QtGui.QLabel(self.tabMinDistance)
        self.label_desc.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_desc.setObjectName(_fromUtf8("label_desc"))
        self.label_img1 = QtGui.QLabel(self.tabMinDistance)
        self.label_img1.setGeometry(QtCore.QRect(30, 80, 60, 60))
        self.label_img1.setMinimumSize(QtCore.QSize(60, 60))
        self.label_img1.setMaximumSize(QtCore.QSize(60, 60))
        self.label_img1.setFrameShape(QtGui.QFrame.Box)
        self.label_img1.setMargin(0)
        self.label_img1.setObjectName(_fromUtf8("label_img1"))
        self.textEdit_info1 = QtGui.QTextEdit(self.tabMinDistance)
        self.textEdit_info1.setGeometry(QtCore.QRect(120, 60, 241, 87))
        self.textEdit_info1.setMinimumSize(QtCore.QSize(241, 87))
        self.textEdit_info1.setObjectName(_fromUtf8("textEdit_info1"))
        self.label_img2 = QtGui.QLabel(self.tabMinDistance)
        self.label_img2.setGeometry(QtCore.QRect(30, 220, 60, 60))
        self.label_img2.setMinimumSize(QtCore.QSize(60, 60))
        self.label_img2.setMaximumSize(QtCore.QSize(60, 60))
        self.label_img2.setFrameShape(QtGui.QFrame.Box)
        self.label_img2.setMargin(0)
        self.label_img2.setObjectName(_fromUtf8("label_img2"))
        self.textEdit_info2 = QtGui.QTextEdit(self.tabMinDistance)
        self.textEdit_info2.setGeometry(QtCore.QRect(120, 200, 241, 87))
        self.textEdit_info2.setMinimumSize(QtCore.QSize(241, 87))
        self.textEdit_info2.setObjectName(_fromUtf8("textEdit_info2"))
        self.label_desc2 = QtGui.QLabel(self.tabMinDistance)
        self.label_desc2.setGeometry(QtCore.QRect(30, 200, 91, 16))
        self.label_desc2.setObjectName(_fromUtf8("label_desc2"))
        self.textEdit_info3 = QtGui.QTextEdit(self.tabMinDistance)
        self.textEdit_info3.setGeometry(QtCore.QRect(120, 340, 241, 87))
        self.textEdit_info3.setMinimumSize(QtCore.QSize(241, 87))
        self.textEdit_info3.setObjectName(_fromUtf8("textEdit_info3"))
        self.label_img3 = QtGui.QLabel(self.tabMinDistance)
        self.label_img3.setGeometry(QtCore.QRect(30, 360, 60, 60))
        self.label_img3.setMinimumSize(QtCore.QSize(60, 60))
        self.label_img3.setMaximumSize(QtCore.QSize(60, 60))
        self.label_img3.setFrameShape(QtGui.QFrame.Box)
        self.label_img3.setMargin(0)
        self.label_img3.setObjectName(_fromUtf8("label_img3"))
        self.label_desc3 = QtGui.QLabel(self.tabMinDistance)
        self.label_desc3.setGeometry(QtCore.QRect(30, 340, 91, 16))
        self.label_desc3.setObjectName(_fromUtf8("label_desc3"))
        self.lineEdit_class1 = QtGui.QLineEdit(self.tabMinDistance)
        self.lineEdit_class1.setGeometry(QtCore.QRect(380, 60, 171, 22))
        self.lineEdit_class1.setObjectName(_fromUtf8("lineEdit_class1"))
        self.label = QtGui.QLabel(self.tabMinDistance)
        self.label.setGeometry(QtCore.QRect(380, 30, 53, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabMinDistance)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_class2 = QtGui.QLineEdit(self.tabMinDistance)
        self.lineEdit_class2.setGeometry(QtCore.QRect(380, 200, 171, 22))
        self.lineEdit_class2.setObjectName(_fromUtf8("lineEdit_class2"))
        self.lineEdit_class3 = QtGui.QLineEdit(self.tabMinDistance)
        self.lineEdit_class3.setGeometry(QtCore.QRect(380, 340, 171, 22))
        self.lineEdit_class3.setObjectName(_fromUtf8("lineEdit_class3"))
        self.label_desc1 = QtGui.QLabel(self.tabMinDistance)
        self.label_desc1.setGeometry(QtCore.QRect(30, 60, 91, 16))
        self.label_desc1.setObjectName(_fromUtf8("label_desc1"))
        self.line_2 = QtGui.QFrame(self.tabMinDistance)
        self.line_2.setGeometry(QtCore.QRect(10, 450, 631, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.groupBox_descriptor = QtGui.QGroupBox(self.tabMinDistance)
        self.groupBox_descriptor.setGeometry(QtCore.QRect(10, 470, 611, 51))
        self.groupBox_descriptor.setFlat(False)
        self.groupBox_descriptor.setCheckable(False)
        self.groupBox_descriptor.setObjectName(_fromUtf8("groupBox_descriptor"))
        self.radioButton_desc1 = QtGui.QRadioButton(self.groupBox_descriptor)
        self.radioButton_desc1.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.radioButton_desc1.setChecked(True)
        self.radioButton_desc1.setObjectName(_fromUtf8("radioButton_desc1"))
        self.radioButton_desc2 = QtGui.QRadioButton(self.groupBox_descriptor)
        self.radioButton_desc2.setGeometry(QtCore.QRect(120, 20, 95, 20))
        self.radioButton_desc2.setObjectName(_fromUtf8("radioButton_desc2"))
        self.radioButton_desc3 = QtGui.QRadioButton(self.groupBox_descriptor)
        self.radioButton_desc3.setGeometry(QtCore.QRect(230, 20, 95, 20))
        self.radioButton_desc3.setObjectName(_fromUtf8("radioButton_desc3"))
        self.groupBox_distance = QtGui.QGroupBox(self.tabMinDistance)
        self.groupBox_distance.setGeometry(QtCore.QRect(10, 530, 611, 51))
        self.groupBox_distance.setObjectName(_fromUtf8("groupBox_distance"))
        self.radioButton_norm1 = QtGui.QRadioButton(self.groupBox_distance)
        self.radioButton_norm1.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.radioButton_norm1.setChecked(True)
        self.radioButton_norm1.setObjectName(_fromUtf8("radioButton_norm1"))
        self.radioButton_norm2 = QtGui.QRadioButton(self.groupBox_distance)
        self.radioButton_norm2.setGeometry(QtCore.QRect(120, 20, 95, 20))
        self.radioButton_norm2.setObjectName(_fromUtf8("radioButton_norm2"))
        self.radioButton_normp = QtGui.QRadioButton(self.groupBox_distance)
        self.radioButton_normp.setGeometry(QtCore.QRect(230, 20, 95, 20))
        self.radioButton_normp.setObjectName(_fromUtf8("radioButton_normp"))
        self.tabWidget.addTab(self.tabMinDistance, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.widget_iconeditor = IconWidget(self.centralwidget)
        self.widget_iconeditor.setGeometry(QtCore.QRect(710, 40, 240, 240))
        self.widget_iconeditor.setMinimumSize(QtCore.QSize(240, 240))
        self.widget_iconeditor.setObjectName(_fromUtf8("widget_iconeditor"))
        self.pbtn_calculate = QtGui.QPushButton(self.centralwidget)
        self.pbtn_calculate.setGeometry(QtCore.QRect(710, 590, 93, 28))
        self.pbtn_calculate.setObjectName(_fromUtf8("pbtn_calculate"))
        self.textEdit_info4 = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_info4.setGeometry(QtCore.QRect(710, 290, 241, 87))
        self.textEdit_info4.setMinimumSize(QtCore.QSize(241, 87))
        self.textEdit_info4.setObjectName(_fromUtf8("textEdit_info4"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(690, 50, 20, 571))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 650, 921, 121))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.lineEdit_icon = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_icon.setGeometry(QtCore.QRect(710, 390, 171, 22))
        self.lineEdit_icon.setObjectName(_fromUtf8("lineEdit_icon"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Pattern Recognition UAG 2013", None))
        self.label_desc.setText(_translate("MainWindow", "Class", None))
        self.label_img1.setText(_translate("MainWindow", "TextLabel", None))
        self.label_img2.setText(_translate("MainWindow", "TextLabel", None))
        self.label_desc2.setText(_translate("MainWindow", "TextLabel", None))
        self.label_img3.setText(_translate("MainWindow", "TextLabel", None))
        self.label_desc3.setText(_translate("MainWindow", "TextLabel", None))
        self.label.setText(_translate("MainWindow", "Distance", None))
        self.label_2.setText(_translate("MainWindow", "Descriptors", None))
        self.label_desc1.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_descriptor.setTitle(_translate("MainWindow", "Descriptor", None))
        self.radioButton_desc1.setText(_translate("MainWindow", "Descriptor 1", None))
        self.radioButton_desc2.setText(_translate("MainWindow", "Descriptor 2", None))
        self.radioButton_desc3.setText(_translate("MainWindow", "Descriptor 3", None))
        self.groupBox_distance.setTitle(_translate("MainWindow", "Distance ", None))
        self.radioButton_norm1.setText(_translate("MainWindow", "Norm 1", None))
        self.radioButton_norm2.setText(_translate("MainWindow", "Norm 2", None))
        self.radioButton_normp.setText(_translate("MainWindow", "Norm P", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMinDistance), _translate("MainWindow", "Minimum Distance", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Perceptron", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Adaline", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "ImageCreator", None))
        self.pbtn_calculate.setText(_translate("MainWindow", "Calculate", None))

from iconwidget import IconWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

